### ISSUE TITLE
error:ValueError: No JSON object could be decoded

### ISSUE THREAD

**Issue by terrificjhony** [AndreaOm/xiaomiquan_bak#1]
提示报错，爬不了：

Traceback (most recent call last):
  File "/Users/mac/Downloads/xiaomiquan_bak-master/xiaomiquan_bak.py", line 67, in <module>
    saveTopics(881542118452) # set bakup group id
  File "/Users/mac/Downloads/xiaomiquan_bak-master/xiaomiquan_bak.py", line 41, in saveTopics
    o = getAllTopics(groupId,getTimeNow())
  File "/Users/mac/Downloads/xiaomiquan_bak-master/xiaomiquan_bak.py", line 57, in getAllTopics
    n = (getTopicsNums(groupId)/20+1)
  File "/Users/mac/Downloads/xiaomiquan_bak-master/xiaomiquan_bak.py", line 65, in getTopicsNums
    return json.loads(requests.get(api + 'groups/' + str(groupId) + '/details', headers=headers , cookies=cookies).content)['resp_data']['group']['statistics']['topics']['topics_count']
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/json/__init__.py", line 338, in loads
    return _default_decoder.decode(s)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/json/decoder.py", line 366, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/json/decoder.py", line 384, in raw_decode
    raise ValueError("No JSON object could be decoded")
ValueError: No JSON object could be decoded

**Comment by AndreaOm** [comment]
```python
File "/Users/mac/Downloads/xiaomiquan_bak-master/xiaomiquan_bak.py", line 65, in getTopicsNums
return json.loads(requests.get(api + 'groups/' + str(groupId) + '/details', headers=headers , cookies=cookies).content)['resp_data']['group']['statistics']['topics']['topics_count']
```

目前看来是第65行报错
可能会有3种原因

1. 网络不好
2. 配置信息不正确
3. 官方api已变更 可以使用chrome查看网页版流量  确认是否是api变更

:D
